In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sentences 
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size 
voc_size=10000

In [5]:
## One Hot Represenation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4217, 4489, 8500, 4010],
 [4217, 4489, 8500, 6213],
 [4217, 8077, 8500, 5082],
 [7824, 489, 7258, 585, 2764],
 [7824, 489, 7258, 585, 673],
 [1593, 4217, 8062, 8500, 4229],
 [2871, 1623, 8144, 585]]

In [6]:
## Word Embedding Representation 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [7]:
import numpy as np

In [8]:
sent_length=8
embedding_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)

In [9]:
embedding_docs

array([[   0,    0,    0,    0, 4217, 4489, 8500, 4010],
       [   0,    0,    0,    0, 4217, 4489, 8500, 6213],
       [   0,    0,    0,    0, 4217, 8077, 8500, 5082],
       [   0,    0,    0, 7824,  489, 7258,  585, 2764],
       [   0,    0,    0, 7824,  489, 7258,  585,  673],
       [   0,    0,    0, 1593, 4217, 8062, 8500, 4229],
       [   0,    0,    0,    0, 2871, 1623, 8144,  585]])

In [10]:
## Feature represenation 
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedding_docs)

1/1 [==============================] - 0s 266ms/step


array([[[ 0.04488787, -0.01905896,  0.02728436,  0.00909592,
         -0.0376116 , -0.03167657, -0.04872792, -0.04224037,
         -0.01438141, -0.00601345],
        [ 0.04488787, -0.01905896,  0.02728436,  0.00909592,
         -0.0376116 , -0.03167657, -0.04872792, -0.04224037,
         -0.01438141, -0.00601345],
        [ 0.04488787, -0.01905896,  0.02728436,  0.00909592,
         -0.0376116 , -0.03167657, -0.04872792, -0.04224037,
         -0.01438141, -0.00601345],
        [ 0.04488787, -0.01905896,  0.02728436,  0.00909592,
         -0.0376116 , -0.03167657, -0.04872792, -0.04224037,
         -0.01438141, -0.00601345],
        [-0.01436176, -0.0249434 , -0.04527485,  0.03143371,
         -0.03377603, -0.01551572,  0.04110597,  0.0428743 ,
          0.04212511,  0.00451352],
        [-0.04330833, -0.04294822,  0.01381366, -0.01555056,
          0.02502925, -0.02123723,  0.0360389 ,  0.02193708,
          0.00732676,  0.02937082],
        [-0.01006048, -0.01421602, -0.0207602 ,  0.0

In [15]:
embedding_docs[0]

array([   0,    0,    0,    0, 4217, 4489, 8500, 4010])

In [16]:
model.predict(embedding_docs[0])

1/1 [==============================] - 0s 103ms/step


array([[ 0.04488787, -0.01905896,  0.02728436,  0.00909592, -0.0376116 ,
        -0.03167657, -0.04872792, -0.04224037, -0.01438141, -0.00601345],
       [ 0.04488787, -0.01905896,  0.02728436,  0.00909592, -0.0376116 ,
        -0.03167657, -0.04872792, -0.04224037, -0.01438141, -0.00601345],
       [ 0.04488787, -0.01905896,  0.02728436,  0.00909592, -0.0376116 ,
        -0.03167657, -0.04872792, -0.04224037, -0.01438141, -0.00601345],
       [ 0.04488787, -0.01905896,  0.02728436,  0.00909592, -0.0376116 ,
        -0.03167657, -0.04872792, -0.04224037, -0.01438141, -0.00601345],
       [-0.01436176, -0.0249434 , -0.04527485,  0.03143371, -0.03377603,
        -0.01551572,  0.04110597,  0.0428743 ,  0.04212511,  0.00451352],
       [-0.04330833, -0.04294822,  0.01381366, -0.01555056,  0.02502925,
        -0.02123723,  0.0360389 ,  0.02193708,  0.00732676,  0.02937082],
       [-0.01006048, -0.01421602, -0.0207602 ,  0.03089206, -0.01166727,
         0.00583601, -0.04048837, -0.04178797